version: '3.8'

services:
  circuitjs1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: circuitjs1-app
    restart: unless-stopped
    environment:
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s